### ISSUE TITLE
After Updating to version 3.2.0 to 3.2.2 miniz lib is missing!!

### ISSUE THREAD

**Issue by ioamas** [m5stack/M5Stack#341]
### Describe the bug

/Users/Coding/Arduino/libraries/M5Core2/src/utility/pngle.c:31:10: fatal error: rom/miniz.h: No such file or directory
   31 | #include <rom/miniz.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

I get this error after updating from version 2.1.4 to all 3.2.xx  versions

### To reproduce

1. Arduino IDE
2. M5core2
3. Compilation

### Expected behavior

---

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [x] My report contains all necessary details

**Comment by TinyuZhao** [comment]
Versions 3.x.x are not supported. Please use M5Unified.
