### ISSUE TITLE
In_eSPI.h: expected unqualified-id before '(' token

### ISSUE THREAD

**Issue by hetlelid** [m5stack/M5Stack#97]
Updated to latest ESP-IDF and arduino-esp32, now getting this error:

> /home/osboxes/esp/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/bits/streambuf.tcc: In >member function 'virtual std::streamsize std::basic_streambuf<_CharT, >_Traits>::xsgetn(std::basic_streambuf<_CharT, _Traits>::char_type*, std::streamsize)':
>/home/osboxes/esp/test/m5_test/components/M5Stack/src/utility/In_eSPI.h:380:20: error: expected >unqualified-id before '(' token
>   #define min(a,b) (((a) < (b)) ? (a) : (b))

I can see that this macro is not recommended:
https://dustri.org/b/min-and-max-macro-considered-harmful.html

However, i have no idea how to fix this. Anyone to guide me?

**Comment by hetlelid** [comment]
Found a workaround. Undefine the macro after `M5Stack.h` is included:

>#include "M5Stack.h"
>#undef min

**Comment by knifter** [comment]
Although maybe not the cause of the error defining min() as this is vulnerable to the double evaluation problem and considered bad practice.
On the other hand, it might very well be..
