### ISSUE TITLE
0.1.9 TFT_eSPI Breaking changes

### ISSUE THREAD

**Issue by tobozo** [m5stack/M5Stack#61]
I put here all the warnings/errors I've found after upgrading to 0.1.9, all are related to the recent TFT_eSPI upgrade, could it be resolved by using wrappers?

- `error: no matching function for call to 'M5Display::drawBitmap(int, int, int, int, uint16_t*)'` with ` candidate expects 6 arguments, 5 provided`
- `error: 'class M5Display' has no member named 'setFont'`
- `error: 'class M5Display' has no member named 'writePixel'`
- `error: 'ILI9341' does not name a type`

I'm not sure for the last error as it comes from a heavily customized sketch, but the error does not occur on 0.1.8.

See this [travis log](https://travis-ci.org/tobozo/M5Stack-SD-Updater/builds/377677309) for more context as it's [compiling 19 representative apps](https://github.com/tobozo/M5Stack-SD-Updater/tree/master/examples/M5Stack-SD-Menu/SD-Apps).

**Comment by 0x1abin** [comment]
Sorry, I left out some drawing methods. I have added some compatible wrappers and re-released v0.1.9.
